
jasypt:
  encryptor:
    password: yorkehan
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  health:
    redis:
      enabled: false
#eureka:
#  #注册中心地址
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8082/eureka/
#    register-with-eureka: false
#  #服务名称
#  instance:
#    appname: boring-common-codegen