spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://10.211.55.5:3306/codegen?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    suffix: .html
    settings:
      classic_compatible: true
      template_exception_handler: rethrow
      template_update_delay:  0
      datetime_format:  yyyy-MM-dd HH:mm
      number_format:  0.##
jasypt:
  encryptor:
    password: yorkehan
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  health:
    redis:
      enabled: false